packages:
  - 'packages/*'
  - 'configs/*'
  - 'packages/gatsby-plugin-abbrlink'
  - 'packages/hexo-plugin-abbrlink'
  - 'packages/eleventy-plugin-abbrlink'
  - 'packages/vuepress-plugin-abbrlink'
  - 'packages/sveltekit-plugin-abbrlink'
  - 'packages/remix-plugin-abbrlink'
